# Built-in

# Custom
title:      "CSS Transformations"
kind:       "article"
excerpt:    "WebKit gains support for CSS transformations, giving it the ability to rotate elements, scale them, skew them, and more. Not a particularly novel concept, but very promising anyway."
oneliner:   "__ONELINER__"
created_at: "Sat Oct 27 10:52:24 +0200 2007"
tags:
  - "webkit"
  - "css"
