# Built-in
builtin:
  filters_pre:
    - "erb"
  layout:     "none"
  extension:  "xml"

# Custom
is_hidden:    "true"
feed_title:   "The Stoneship Journal"
feed_url:     "http://feeds.feedburner.com/stoneship"
title:        "The Stoneship Journal"
