output_dir: "output"
base_url:   "http://stoneship.org"
data_sources:
  - type: filesystem_compact
deploy:
  default:
    dst:     "ectype:sites/stoneship/public"
    options: [ '-gpPrvz', '--exclude=".hg"' ]
