# Built-in
layout:       "default"
extension:    "html"
filters_pre:  [ 'erb' ]
filters_post: [ 'rubypants' ]

# Custom
base_url:             "http://stoneship.org"
display_title:        "true"
author_name:          "Denis Defreyne"
author_uri:           "http://stoneship.org/"
scripts:              []
