# Built-in
layout:       "default"
extension:    "html"
filters_pre:  [ 'erb' ]
filters_post: []

# Custom
base_url:             "http://stoneship.org"
display_title:        "true"
display_sidebar:      "true"
display_breadcrumbs:  "true"
enable_comments:      "false"
author_name:          "Denis Defreyne"
author_uri:           "http://stoneship.org/"
am_i_for_hire:        "false"
scripts:
  - "/media/scripts/jquery-1.2.1.pack.js"
  - "/media/scripts/comments.js"
