# Built-in

# Custom
title:      "Alurio is Dead"
kind:       "article"
excerpt:    "Today, I'm declaring Alurio dead, after over four years of development without a single public release. I'm also introducing Lunkwill."
oneliner:   "don't keep waiting for a release&mdash;it's over"
created_at: "Mon Sep 24 21:41:39 +0200 2007"
tags:
  - "alurio"
  - "lunkwill"
