# Built-in

# Custom
title:      "A New Cam"
kind:       "article"
excerpt:    "About two weeks ago, I got myself a Nikon D40. Here's a collection of random photos I've captured so far."
oneliner:   "photos from my new Nikon D40 SLR"
created_at: "Wed Jul 25 18:55:09 +0200 2007"
tags:
  - "nikon"
  - "camera"
  - "photography"
