# Built-in
filters_pre:
  - "maruku"

# Custom
title:      "From Rails back to PHP"
kind:       "article"
excerpt:    "David Sivers <a href=\"http://www.oreillynet.com/ruby/blog/2007/09/7_reasons_i_switched_back_to_p_1.html\">switched from Ruby on Rails back to PHP</a>, listing seven reasons why he likes PHP better. I disagree with most of his assertions."
oneliner:   "7 ungrounded reasons."
created_at: "Sun Sep 23 21:59:49 +0200 2007"
tags:
  - "ruby"
  - "php"
  - "rails"
