# Built-in

# Custom
title:    "Bloatware Ad"
kind:     "article"
excerpt:  "The interactive Adobe Creative Suite 3 advertisement on Layer Tennis yells \"bloatware!\" like never seen before."
oneliner: "Take as much as you want."
created_at: "2007-09-29 11:40:00"
tags:
  - "cs3"
  - "advertisement"
