# Built-in

# Custom
title: "Meaningful Markup"
kind: "article"
excerpt: "Many people create web sites based on what they want it to look like. This is quite annoying for people browsing the web using non-visual methods, and it doesn't please search engines either. Meaningful markup to the rescue!"
oneliner: "getting to know the benefits of good HTML"
created_at: "2006-11-18 00:30:00"
