# Built-in
filters_pre:
  - "markdown"
  - "smartypants"

# Custom
title: "I am a Cyantist"
kind: "article"
excerpt: "A couple of weeks ago, <a href=\"http://thegreydragon.com/\">Ryan Warzecha</a> asked me whether I was interested in doing some web-related work for <a href=\"http://www.cyan.com/\">Cyan Worlds</a> (the company that made Myst). I said yes, and now I&#8217;m doing an internship, along with <a href=\"http://grey-skies.net/\">Keith Lord</a>."
oneliner: "how I became an intern at Cyan"
created_at: "2007-09-18 21:30:00"
tags:
  - "cyan"
  - "myst"
  - "uru"
