# Built-in

# Custom
title: "C Reference Counting and You"
kind: "article"
excerpt: "Manual memory management using <code>malloc()</code> and <code>free()</code> works nicely, but can become tiresome. Enter reference counting — makes memory management a lot easier."
oneliner: "easier management using references"
created_at: "2007-02-08 01:30:00"
