# Built-in

# Custom
title:            "Introducing nanoc"
kind:             "article"
excerpt:          "nanoc is a small CMS that doesn't run on your server. Here's how it works: you write your site on your local computer, you compile the site, and then you upload it to your server."
oneliner:         "a CMS that doesn't run on your server"
created_at:       "Fri May 04 13:10:00 +0200 2007"
tags:
  - "nanoc"
  - "ruby"
  - "cms"
